version: 2
updates:
  - package-ecosystem: npm
    directory: /
    commit-message:
      prefix: 'chore(deps)'
    schedule:
      interval: weekly
      day: monday
      time: '05:00'
      timezone: Europe/Oslo
    groups:
      storybook:
        patterns:
          - 'storybook'
          - '@storybook/*'
          - 'eslint-plugin-storybook'
        update-types:
          - major
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
        update-types:
          - major
      react-aria:
        patterns:
          - 'react-aria'
          - '@react-aria/*'
          - '@react-stately/*'
          - '@react-types/*'
          - '@internationalized/*'
        update-types:
          - major
      rollup:
        patterns:
          - 'rollup'
          - '@rollup/*'
          - 'rollup-plugin-*'
        update-types:
          - major
      tanstack:
        patterns:
          - '@tanstack/*'
        update-types:
          - major
      eslint:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@typescript-eslint/*'
          - '@eslint/*'
        update-types:
          - major
      testing:
        patterns:
          - 'jest'
          - 'jest-*'
          - '@testing-library/*'
          - '@types/jest'
          - '@playwright/test'
        update-types:
          - major
      all-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    versioning-strategy: increase
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: 'chore(deps)'
    schedule:
      interval: weekly
      day: monday
      time: '05:00'
      timezone: Europe/Oslo
    groups:
      all-actions:
        patterns:
          - '*'
        update-types:
          - major
          - minor
          - patch
