apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: eds
spec:
  build:
    useBuildKit: true
    useBuildCache: true
  environments:
    - name: prod
      build:
        from: main
    - name: dev
      build:
        from: feat/*
  dnsAppAlias:
    environment: prod
    component: docs
  dnsAlias:
    - alias: eds
      environment: prod
      component: docs
  dnsExternalAlias:
    - alias: eds.equinor.com
      environment: prod
      component: docs
      useCertificateAutomation: true
  components:
    - name: color-palette-generator
      dockerfileName: DockerfileColorPaletteGenerator
      publicPort: http
      ports:
        - name: http
          port: 3000
    - name: docs
      dockerfileName: DockerfileEdsDocs
      publicPort: http
      ports:
        - name: http
          port: 3000
