name: eds-tokens-$(Build.BuildId)

pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: 'true'
  branches:
    include:
      - develop
      - typescript
      - theming
  paths:
    include:
      - libraries/eds-tokens

pr:
  branches:
    include:
      - develop
      - typescript
      - theming
  paths:
    include:
      - libraries/eds-tokens

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: npm install -g pnpm@next
    displayName: 'Install pnpm'

  - script: >-
      pnpm
      --filter eds
      --filter ./libraries/eds-tokens
      install
    displayName: 'Install dependencies'

  - script: pnpm --filter ./libraries/eds-tokens run build
    displayName: 'Run build'

  - script: >-
      ./node_modules/eslint/bin/eslint.js
      ./libraries/eds-tokens
    displayName: 'Run eslint'
