# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: eds-react-$(Build.BuildId)

pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: 'true'
  branches:
    include:
      - develop
      - typescript
      - theming
  paths:
    include:
      - libraries/eds-core-react

pr:
  branches:
    include:
      - develop
      - typescript
      - theming
  paths:
    include:
      - libraries/eds-core-react

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: npm install -g pnpm@next
    displayName: 'Install pnpm'

  - script: >-
      pnpm
      --filter eds
      --filter ./libraries/tokens
      --filter ./libraries/icons
      --filter ./libraries/eds-core-react
      install
    displayName: 'Install dependencies'

  - script: pnpm --filter ./libraries/eds-core-react test
    displayName: 'Run tests'

  - script: >-
      ./node_modules/eslint/bin/eslint.js
      ./libraries/eds-core-react
    displayName: 'Run eslint'
