name: Publish assets to cdn
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for the cdn'
        required: false
        type: choice
        options:
          - development
          - production
        default: 'development'

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  copy-files:
    name: Copy files from GitHub to cdn
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout cdn repo üõéÔ∏è
        id: checkout-cdn-repo
        uses: actions/checkout@v3
        with:
          repository: 'equinor/design-system-cdn'
          ref: main
          ssh-key: ${{ secrets.CDN_REPO_PRIVATE_KEY }}
      - name: Az CLI login üîë  # Use federated credential
        uses: azure/login@v1
        with:
          client-id: d58b2e85-2d34-4cdb-ad70-5f2b767dd8e2
          tenant-id: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
          allow-no-subscriptions: true
      - name: Upload files üìÇ
        id: upload-files
        uses: azure/CLI@v1
        with:
        # Need to find out if cli login is good enough
          inlineScript: |
            az storage blob sync -c ${{ vars.AZURE_ARTEFACTS_CONTAINER }} -s assets --connection-string ${{ secrets.AZURE_ARTEFACTS_CONNECTION_STRING }}
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name ${{ vars.AZURE_CDN_PROFILE_NAME }} --name ${{ vars.AZURE_CDN_ENDPOINT_NAME }} --resource-group ${{ vars.AZURE_RESOURCE_GROUP }}
      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
      - name: log-errors-to-slack
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
